"""initial schema

Revision ID: 02ab532e02a5
Revises: 
Create Date: 2026-09-26 21:09:50.043658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ab532e02a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('recipes', sa.String(length=150), nullable=False),
    sa.Column('ingredients', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cook_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cook_recipes'), ['recipes'], unique=False)
        batch_op.create_index(batch_op.f('ix_cook_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cook_title'))
        batch_op.drop_index(batch_op.f('ix_cook_recipes'))
        batch_op.drop_index(batch_op.f('ix_cook_id'))

    op.drop_table('cook')
    # ### end Alembic commands ###
