"""add author_id to cook

Revision ID: 3cc0317d9d5c
Revises: 02ab532e02a5
Create Date: 2026-09-28 23:32:53.472399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc0317d9d5c'
down_revision: Union[str, Sequence[str], None] = '02ab532e02a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('index', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_name'), ['name'], unique=False)

    with op.batch_alter_table('cook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cook_author_id_recipes'), 'recipes', ['author_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cook', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cook_author_id_recipes'), type_='foreignkey')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_name'))
        batch_op.drop_index(batch_op.f('ix_recipes_id'))

    op.drop_table('recipes')
    # ### end Alembic commands ###
