"""add genres and cook_genre many to many table

Revision ID: c05e33c10c7e
Revises: 00a145999928
Create Date: 2026-09-30 01:18:42.153652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05e33c10c7e'
down_revision: Union[str, Sequence[str], None] = '00a145999928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_genres_name'), ['name'], unique=False)

    op.create_table('cook_genre',
    sa.Column('cook_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cook_id'], ['cook.id'], name=op.f('fk_cook_genre_cook_id_cook'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_cook_genre_genre_id_genres'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cook_id', 'genre_id', name=op.f('pk_cook_genre'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cook_genre')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_name'))
        batch_op.drop_index(batch_op.f('ix_genres_id'))

    op.drop_table('genres')
    # ### end Alembic commands ###
